name: room_ranger
description: "Свободные даты для бронирования"
publish_to: 'none'
version: 0.2.2+14

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
