name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION_NUMBER=${VERSION#v}
          echo "version=$VERSION_NUMBER" >> $GITHUB_OUTPUT
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Room Ranger ${{ steps.version.outputs.version_number }}
          body: |
            ## Что нового в версии ${{ steps.version.outputs.version_number }}
            
            ### Изменения
            - Обновления и улучшения
            
            ### Технические детали
            - Версия сборки: ${{ steps.version.outputs.version_number }}
            - Дата сборки: ${{ github.event.head_commit.timestamp }}
            
            ### Скачать
            - [Веб-версия](https://${{ github.repository_owner }}.github.io/room_ranger/)
          draft: false
          prerelease: false 